server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_PAYMENT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

logging:
  level:
    com.reynan.paymentservice: DEBUG
